clang -O3 -fPIC -g -DUSE_DL_PREFIX=1 -DUSE_LOCKS=0 -DUSE_OS_MORE_CORE=1 -DONLY_STORED_MAPPED_PAGE=1 -DMORECORE=osMoreCore  -DFOOTERS=1 -DMORECORE_CANNOT_TRIM=1 -DHAVE_MREMAP=0 -DHAVE_MMAP=0 -DNO_MALLINFO=1 -DNO_MALLOC_STATS=1 -shared dlmalloc.c -o libmalloc.so

